#!/bin/bash
function p () 
{ 
	((q)) || { 
		i=
		while (($#)); do
			((t)) && i+=$2 || i+=\\e[$1m$2\\e[0m
			shift 2
		done
		printf "$i\n"
	}
}
function q () 
{ 
	p "$@"
	[ -e "$b" ] && rm $b
	exit 1
}
function d () 
{ 
	q=0 q 0 Err:\  "$@\n\n" 31 安装失败,请重试...
}
function c () 
{ 
	c=_$(COLUMNS=32 curl --connect-timeout 10 -L#w%{http_code} $url$@)
	[ $c = _200 ] || { 
		[ $c = _404 ] && d 33 下载失败,请检查输入是否正确... || d 33 连接失败,请检查网络\(代理\)是否可用...
	}
}
exec 2>&1
trap 'q 31 \\n强制中断...' 1 2 9 15
tty -s
t=$? l= d= p= q=0 s=0
url=https://raw.github.com/WQY916/F/main/
termux-wake-lock
[ -w /sdcard/ ] || termux-setup-storage
[ -w /sdcard/ ] || d 33 存储读写授权失败...
(($#)) || set -- $opt
while getopts :d:gl:p:qs k; do
	v=$OPTARG
	case $k in 
		q)
			q=1
		;;
		l)
			l=${l/$v /}$v\ 
		;;
		d)
			d=${d/$v /}$v\ 
		;;
		p)
			p=${p/$v /}$v\ 
		;;
		s)
			p=${p/php /}php\  s=1
		;;
		g)
			url=https://gitlab.com/WQY916/F_gitlab/-/raw/main/
		;;
		*)
			q 0 错误参数:\  1\;33 -$v 0 ...
		;;
	esac
done
shift $((OPTIND - 1))
(($#)) && q 0 无效参数:\  1\;33 "$*" 0 ...
[[ -n $l$d$p ]] || q 33 请指定安装任务...
((${#p})) && { 
	p 1\;37 获取内部软件:
	p=${p% } c=/data/data/com.termux/cache/apt/pkgcache.bin
	apt-get indextargets | grep -q stable && [ -e $c ] && (($(date +%s) < $(stat -c%X $c) + 43200)) && p 0 缓存较新,跳过... || { 
		p 0 更新软件源...
		apt-get update || d 33 更新失败,无法安装所需依赖,请检查软件源和网络\(代理\)是否可用...
	}
	p 0 \\n安装软件包:\  1\;33 "${p// /, }" 0 ...
	apt-get install -y $p || d 33 安装失败,请检查输入是否正确...
	p
}
((${#d})) && { 
	p 1\;37 下载静态软件:
	a=$(uname -m)
	[ $a = arm* ] && a=arm || [ $a = aarch64 ] || d 0 不支持的架构:\  1\;31 $a 0 ...
	p 0 当前架构:\  1\;33 $a 0 ...
	for u in $d
	do
		b=$u\_$a.tar.xz
		p 0 \\n下载软件包:\  1\;33 $u 0 ...
		c bin/$b -O
		tar xvJf $b -C $PREFIX/bin || d 33 解压失败,命令不可用或压缩包不完整...
		rm $b
	done
	p
}
((${#l})) && { 
	p 1\;37 下载依赖文件:
	for u in $l
	do
		b=$u.tar.xz
		p 0 \\n下载依赖包:\  1\;33 $u 0 ...
		c lib/$b -O
		tar xvJf $b -C $PREFIX || d 33 解压失败,命令不可用或压缩包不完整...
		rm $b
	done
	p
}
((s)) && { 
	p 1\;37 创建配置文件:
	mkdir -p ~/.config
	f=~/.config/fv_cmd.php x=$PREFIX/bin/fvserver
	echo '<?php header("Access-Control-Allow-Origin: *");header("Content-Type: text/html; charset=utf-8");passthru("$_REQUEST[v]") ?>' > $f
	echo "termux-wake-lock;nice -n-20 php -qS0.0.0.0:8888 $f &" > $x
	chmod +x $x
	p 33 \\n运行 1\;4\;33 fvserver 33 用以启动WEB服务...
	p
}
p 1\;32 安装完成...
exit 0
