#!/bin/bash
function p () 
{ 
	((q)) || { 
		i=;
		while (($#)); do
			((t)) && i+=$2 || i+="\e[$1m$2\e[0m";
			shift 2;
		done;
		printf "$i\n"
	}
};
function q () 
{ 
	p "$@";
	[ -e "$b" ] && rm $b;
	exit 1
};
function d () 
{ 
	q=0 q "$@\n\n" 31 安装失败,请重试...
};
exec 2>&1;
trap 'q 31 \\n强制中断...' 1 2 9 15;
tty -s;
t=$? d= p= q=0 s=0;
termux-wake-lock;
[ -w /sdcard/ ] || termux-setup-storage;
[ -w /sdcard/ ] || d 33 存储读写授权失败...;
(($#)) || set -- $opt;
while getopts :d:p:qs k; do
	v=$OPTARG;
	case $k in 
		q)
			q=1
		;;
		d)
			d=${d/$v /}$v\ 
		;;
		p)
			p=${p/$v /}$v\ 
		;;
		s)
			p=${p/php /}php\  s=1
		;;
		*)
			q 0 错误参数:\  1\;33 -$v 0 ...
		;;
	esac;
done;
shift $((OPTIND-1));
(($#)) && q 0 无效参数:\  1\;33 "$*" 0 ...;
[[ -n $d$p ]] || q 33 请指定安装任务...;
((${#p})) && { 
	p 1\;37 内部源:;
	p=${p% } l=/data/data/com.termux/cache/apt/pkgcache.bin;
	apt-get indextargets | grep -q stable && [ -e $l ] && ((`date +%s`<`stat -c%X $l`+43200)) && { 
		p 0 缓存较新,跳过...
	} || { 
		p 0 更新软件源...;
		apt-get update || d 33 更新失败,\\n无法安装所需依赖,\\n请检查软件 源和网络\(代理\)是否可用...
	};
	p 0 \\n安装软件包:\  1\;33 "${p// /, }" 0 ...;
	COLUMNS=32 apt-get install -y $p || d 33 安装失败,\\n请检查输入是否正确...;
	p
};
((${#d})) && { 
	p 1\;37 外部源:;
	a=`uname -m`;
	[ $a = arm* ] && a=arm || [ $a = aarch64 ] || d 0 不支持的架构:\  1\;31 $a 0 ...;
	p 0 当前架构:\  1\;33 $a 0 ...;
	for u in $d;
	do
		p 0 \\n下载软件包:\  1\;33 $u 0 ...;
		b=$u\_$a.tar.xz c=_`COLUMNS=32 curl --connect-timeout 10 -#Ow%{http_code} https://raw.githubusercontent.com/WQY916/script/main/bin/$b`;
		[ $c = _200 ] && { 
			tar xf $b -C $PREFIX/bin || d 33 解压失败,\\n命令不可用或压缩包不完整...;
			rm $b
		} || { 
			[ $c = _404 ] && d 33 下载失败,\\n请检查输入是否正确... || d 33 连接失败,\\n请检查网络\(代理\)是否可用...
		};
	done;
	p
};
((s)) && { 
	p 1\;37 创建配置文件:;
	mkdir -p ~/.config;
	f=~/.config/fv_cmd.php x=$PREFIX/bin/fvserver;
	echo '<?php header("Connection: keep-alive");header("Access-Control-Allow-Origin: *");header("content-type: text/html;charset=utf-8");system($_GET["v"]) ?>' > $f;
	echo "termux-wake-lock;nice -n-20 php -qS0.0.0.0:8888 $f &" > $x;
	chmod +x $x;
	p 33 \\n运行 1\;4\;33 fvserver 33 用以启动WEB服务...;
	p
};
p 1\;32 安装完成...;
exit 0
